name: 'Obrigado Action'
description: 'Dizer "Obrigado" para novos pull requests'
author: 'Feliphe Vinicius'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API Token'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
